In [24]:
import numpy as np
import matplotlib.pyplot as plt

import sys, os

sys.path.insert(0, '/Users/sam/PycharmProjects/Quantum-Control/NewModule')
from arc import *  # Import ARC (Alkali Rydberg Calculator)
atom = Calcium40()
calc = StarkMap(atom)

In [25]:
n = 35
l = 3
j = 3
mj = 0
s = 0
nmin = n - 1
nmax = n + 1
lmax = nmax - 1
calc.defineBasis(n,l,j,mj,nmin,nmax,lmax,s=s)
efield = [0,500,1000,2000]
calc.diagonalise(efield)

In [26]:
# maintenant on cherche à calculer les coefficients de mélange
# que nous donne composition ?
# composition est composé de 4 arrays, 1 par valeur de champ électrique sur lequel on a diagonalisé. composition[i]
# a l'interieur de 1 des array (par exemple composition[0]), on a une liste, qui a chaque element, donne la decomposition de l'etat stark en fonction des etats de la base atomique
## test, le compo[0][2] = [-1,34], comment ça se fait ? Probablement que en diagonalisant, on a change la position de l'etat 2 avec l'etat 34. On peut verifier cela. Il faudrait que le 34 eme elts de l'hamiltonien diagonal, soit le 3eme dans y (eigenenergies). Regardons ça (plus exactement, cela fonctionne seulement quand le champ electrique est nul).

print(calc.y[1])
print(len(calc.egvector[1]))
print(calc.egvector[1])
## ok c'est bon.
# a l'interieur de chacun de ses array, on a n elements qui correspondent au nombre d'etats atomiques presents dans l'etat Stark
# MAIS composition ne dit pas quel etat Stark est le plus peuplé. Pour trouver ca, on regarde egvector ? Essayons.
x = 0
xx = 0
for value in calc.egvector[1]:
    x += value
    xx += np.abs(value)
print(x)
print(xx)
x = 0
xx = 0
for value in calc.egvector[2]:
    x += value
    xx += np.abs(value)
print(x)
print(xx)
x = 0
xx = 0
for value in calc.egvector[3]:
    x += value
    xx += np.abs(value)
print(x)
print(xx)
x = 0
xx = 0
# ok

[-3281.83122821 -3189.70355927 -3083.87123756 -2999.79283393
 -2865.49318952 -2856.19972952 -2855.41775352 -2854.6691545
 -2853.93621431 -2853.21270254 -2852.49562919 -2851.78332504
 -2851.07477798 -2850.36935275 -2849.66666272 -2848.96651995
 -2848.26894589 -2847.57426641 -2846.88339901 -2846.19871555
 -2845.52702369 -2844.89141391 -2844.3518216  -2843.85697528
 -2843.25849769 -2842.59923497 -2841.91962348 -2841.23139664
 -2840.53813161 -2839.840898   -2839.13971819 -2838.4339468
 -2837.7222229  -2837.00199294 -2836.26791714 -2835.50478826
 -2704.3784089  -2696.46285443 -2695.65991205 -2694.89276489
 -2694.14274974 -2693.40317254 -2692.67071919 -2691.94345778
 -2691.22014997 -2690.49996096 -2689.782326   -2689.06689402
 -2688.35352432 -2687.64234298 -2686.93391016 -2686.22966346
 -2685.53316624 -2684.85397417 -2684.21835931 -2683.66021695
 -2683.10557245 -2682.47256818 -2681.79232864 -2681.09245824
 -2680.38306552 -2679.66783523 -2678.94812612 -2678.22424087
 -2677.49579053 -2676.7616

In [27]:
basis_size = len(calc.basisStates)
new_basis = np.zeros_like(calc.basisStates)
for i in range(basis_size):
    new_basis[i] = calc.basisStates[calc.index_new_basis[i]]


[[34.  0.  0.  0.]
 [34.  1.  1.  0.]
 [35.  0.  0.  0.]
 [34.  4.  4.  0.]
 [35.  1.  1.  0.]
 [34.  5.  5.  0.]
 [34.  6.  6.  0.]
 [34.  7.  7.  0.]
 [34.  8.  8.  0.]
 [34.  9.  9.  0.]
 [34. 10. 10.  0.]
 [34. 11. 11.  0.]
 [34. 12. 12.  0.]
 [34. 13. 13.  0.]
 [34. 14. 14.  0.]
 [34. 15. 15.  0.]
 [34. 16. 16.  0.]
 [34. 17. 17.  0.]
 [34. 18. 18.  0.]
 [34. 19. 19.  0.]
 [34. 20. 20.  0.]
 [34. 21. 21.  0.]
 [34. 22. 22.  0.]
 [34. 23. 23.  0.]
 [34. 24. 24.  0.]
 [34. 25. 25.  0.]
 [34. 26. 26.  0.]
 [34. 27. 27.  0.]
 [34. 28. 28.  0.]
 [34. 29. 29.  0.]
 [34. 30. 30.  0.]
 [34. 31. 31.  0.]
 [34. 32. 32.  0.]
 [34. 33. 33.  0.]
 [34.  2.  2.  0.]
 [34.  3.  3.  0.]
 [35.  3.  3.  0.]
 [35.  2.  2.  0.]
 [35.  4.  4.  0.]
 [35.  5.  5.  0.]
 [35.  6.  6.  0.]
 [35.  7.  7.  0.]
 [35.  8.  8.  0.]
 [35.  9.  9.  0.]
 [35. 10. 10.  0.]
 [35. 11. 11.  0.]
 [35. 12. 12.  0.]
 [35. 13. 13.  0.]
 [35. 14. 14.  0.]
 [35. 15. 15.  0.]
 [35. 16. 16.  0.]
 [35. 17. 17.  0.]
 [35. 18. 18

In [57]:
# mtn qu'on sait que les coeff de Stark sont donnés par egvector. Donc on va pouvoir commencer a s'amuser.
# soit un atome de ca dans un etat 35F^3, on se demande ce qu'il se passe si on applique plusieurs pulse. Ici on ignore la partie temporelle du système.
# comment on va fonctionner ?
# 1. on applique le premier pulse F1 : ce pulse va impliquer un effet Stark, donc melange des niveaux atomiques (niveau stark)
# 2. eteindre le champ electrique F1 : après avoir éteind directement le champ, les etats Stark vont se projeter directement sur les etats atomiques
# 3. application d'un nouveau champ electrique F2 : cette fois, on prend les coefficients des niveaux Stark comme etat initial du système, et on regarde l'evolution des etats
# eteindre le champ electrique F2.
# etc....

#_____________________________1.
#on va faire un peu de recyclage et réutiliser les valeurs calculer précédemment. efield = 0.5,1.0,2.0
initial_psi = np.zeros(len(calc.basisStates))
# on doit aller pacer un 1 dans l'état qui correspond à notre état 35F3. on a déjà diagonaliser donc on doit aller chercher dans index_new basis.
initial_psi[calc.index_new_basis[calc.indexOfCoupledState]] = 1
total_population = np.zeros(4)
for i in range(len(calc.basisStates)):
    total_population[0] += initial_psi[i]
#2.____________________________

compo_stark_first_pulse = calc.composition[1]
##########from_initial_state_to_compo_stark_first_pulse = compo_stark_first_pule * initial_psi
pop_stark_first_pulse = calc.egvector[1]
projected_atomic_population = np.zeros(len(calc.basisStates))
for i in range(basis_size):
    z = pop_stark_first_pulse[i]
    for j in range(len(compo_stark_first_pulse[i])):
        x = 0
        z = pop_stark_first_pulse[i]
        y = compo_stark_first_pulse[i][j][0]*initial_psi[i]
        x = z * y
        #print(y)
        #if y != 0:
            #print("z,y=",z,y,"x=",x)
        # on doit reussir a rajouter ce resultat dans un tableau qui reprendrait toutes les populations de la base atomique MAIS qui serait reecrite dans l'ordre de calcul de la diagonalisation (pas le même ordre)
        #print('y,z=',y,z,'x=',x)
        projected_atomic_population[compo_stark_first_pulse[i][j][1]] += x
        # on doit reussir a rajouter ce resultat dans un tableau qui reprendrait toutes les populations de la base atomique MAIS qui serait reecrite dans l'ordre de calcul de la diagonalisation (pas le même ordre)
#print(projected_atomic_population)
#print(calc.basisStates[37])
#print(projected_atomic_population.max())
abs_projected_atomic_population = np.abs(projected_atomic_population)
for i in range(basis_size):
    total_population[1] += abs_projected_atomic_population[i]

#print(abs_projected_atomic_population.max())
i = 0
non_zero_index = []

#3.____________________________

compo_stark_second_pulse = calc.composition[2]
#notre état initial est donné par projected_atomic_population

#initial_psi = np.array([initial_psi,projected_atomic_population])
initial_psi_second_pulse = projected_atomic_population
pop_stark_second_pulse = calc.egvector[2]
projected_atomic_population = np.zeros(len(calc.basisStates))
for i in range(basis_size):
    z = pop_stark_second_pulse[i]
    for j in range(len(compo_stark_second_pulse[i])):
        x = 0
        z = pop_stark_second_pulse[i]
        y = compo_stark_second_pulse[i][j][0]*initial_psi_second_pulse[i]
        x = z * y
        #if y != 0:
            #print("z,y=",z,y,"x=",x)
        projected_atomic_population[compo_stark_first_pulse[i][j][1]] += x
abs_projected_atomic_population = np.abs(projected_atomic_population)
#print(abs_projected_atomic_population.max())
i = 0
non_zero_index = []
#for i in range(len(abs_projected_atomic_population)):
    #if projected_atomic_population[i] != 0:
        #print(projected_atomic_population[i])

    #else:
    #    pass
for i in range(basis_size):
    total_population[2] += abs_projected_atomic_population[i]
#4______________
#third pulse

compo_stark_third_pulse = calc.composition[3]
initial_psi_third_pulse = projected_atomic_population
pop_stark_third_pulse = calc.egvector[3]
projected_atomic_population = np.zeros(len(calc.basisStates))
for i in range(basis_size):
    z = pop_stark_third_pulse[i]
    for j in range(len(compo_stark_third_pulse[i])):
        x = 0
        z = pop_stark_third_pulse[i]
        y = compo_stark_third_pulse[i][j][0]*initial_psi_third_pulse[i]
        x = z*y
        #if y != 0:
            #print("z,y=",z,y,"x=",x)
        projected_atomic_population[compo_stark_third_pulse[i][j][1]] += x
abs_projected_atomic_population = np.abs(projected_atomic_population)
for i in range(basis_size):
    #print(abs_projected_atomic_population[i])
    total_population[3] += abs_projected_atomic_population[i]
i = 0
non_zero_index = []
#for i in range(len(abs_projected_atomic_population)):
    #if projected_atomic_population[i] != 0:
        #print(projected_atomic_population[i])
    #else:
        #pass
